name: CI_STORE_DEPLOY_ANDROID

on:
  push:
    branches: [master]

jobs:
  store_deploy_android:
    # if: startsWith(github.ref, 'refs/heads/release/')
    name: android store release
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '21.0.4'
      FLUTTER_VERSION: '3.27.1'
      AAB_PATH: build/app/outputs/bundle/release/app-release.aab
      KEYSTORE_PATH: android/upload-keystore.jks
      KEY_PROPS_PATH: android/key.properties
      SERVICE_ACCOUNT_PATH: store_credentials.json

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Setup Java to compile the Android project
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Decode Android keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > ${{ env.KEYSTORE_PATH }}

      - name: Decode Android key properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTY }}" | base64 --decode > ${{ env.KEY_PROPS_PATH }}

      - name: Decode Android Service Account
        run: echo "${{ secrets.SERVICE_JSON }}" | base64 --decode > ${{ env.SERVICE_ACCOUNT_PATH }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build aab
        run: flutter build appbundle --release

      - name: Upload generated aab to the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aab-stores
          path: ${{ env.AAB_PATH }}

      - name: Deploy to Play Store (Internal testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ env.SERVICE_ACCOUNT_PATH }}
          packageName: com.ketsuna.com
          releaseFiles: ${{ env.AAB_PATH }}
          track: internal
