name: Build and Release Flutter Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows
      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/runner/Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build macos
      - name: Upload macOS Build
        uses: actions/upload-artifact@v2
        with:
          name: macos-build
          path: build/macos/Build/Products/Release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter pub get
      - run: flutter build linux
      - name: Upload Linux Build
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: build/linux/x64/release/bundle

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v4
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/*.apk

  create-release:
    needs: [build-windows, build-macos, build-linux, build-ios, build-android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v2
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "android-build/*.apk,windows-build/*,macos-build/*,linux-build/*,ios-build/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
